---
# Source: ingress-nginx/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.11.3
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-controller
    app.kubernetes.io/version: "1.11.3"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-controller-ingress-nginx-controller
  namespace: nginx
data:
  allow-snippet-annotations: "false"
  hsts: "false"
  proxy-real-ip-cidr: "0.0.0.0/0"
  server-tokens: "false"
  use-forwarded-headers: "true"
