apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- controller-configmap.yaml
- controller-daemonset.yaml
- controller-ingressclass.yaml
- controller-poddisruptionbudget.yaml
- controller-role.yaml
- controller-rolebinding.yaml
- controller-service-webhook.yaml
- controller-service.yaml
- controller-serviceaccount.yaml
- namespace.yaml
- ./admission-webhooks
- ./admission-webhooks/job-patch
