apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- job-createSecret.yaml
- job-patchWebhook.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
